### ISSUE TITLE
Check if element present before adding autocomplete to it

### ISSUE THREAD

**Issue by maxf** [alphagov/accessible-typeahead#107] opened 2017-05-09 10:35 UTC
If the autocomplete code is added to a page:
```accessibleTypeahead.enhanceSelectElement({
  selectElement: document.querySelector('#location-picker')
})
```
But no `#location-picker` is present, it produces an error. It should do nothing if it finds the element isn't on the page.

**Comment by tvararu** [comment] 2017-05-09 10:39
> It should do nothing if it finds the element isn't on the page.

Why?

**Comment by maxf** [comment] 2017-05-09 16:12
Just like jQuery does nothing if you do `$('#doesntexist').hide()`

**Comment by tvararu** [comment] 2017-05-09 16:31
@maxf I think this is a matter of opinion, and it's true that lots of JavaScript libraries produce silent failures, but I prefer the opposite. I want libraries to to complain when they are being used incorrectly, with good error messages to help get you on track.

Will close this for now as it's not a bug, but please feel free to comment if you have evidence to suggest silent failures are a better approach.

**Closed by tvararu** 2017-05-09 16:31 UTC
Labels: bug

**Comment by maxf** [comment] 2017-05-10 09:58
Fair enough. A clearer error message would help though.

**Comment by tvararu** [comment] 2017-05-10 12:11
@maxf definitely, I've opened https://github.com/alphagov/accessible-typeahead/pull/111
